#!/usr/bin/env bash
set -e

# install updated version of code-server
VERSION=4.100.3
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xz
ln -s /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -


# default behavior: extensions are installed here and reinstalled when capsule is rebuilt,
# alternative: install extensions manually inside capsule filesystem, saved across rebuilds
install_extensions=true

if $install_extensions; then
  mkdir -p /.vscode/extensions
  code-server --extensions-dir=/.vscode/extensions --install-extension ms-toolsai.jupyter 
  code-server --extensions-dir=/.vscode/extensions --install-extension ms-python.python 
  code-server --extensions-dir=/.vscode/extensions --install-extension detachhead.basedpyright
else
  # move VS code extensions directory into capsule and symlink
  # (this may cause issues on the first run that will be solved by reloading VS code
  echo "mkdir -p /root/capsule/.vscode/extensions" >> /root/.profile
  ln -s /root/capsule/.vscode /.vscode
  # install extensions manually, or run the below lines in the terminal of cloud workstation
#   code-server --extensions-dir=/.vscode/extensions --install-extension ms-toolsai.jupyter 
#   code-server --extensions-dir=/.vscode/extensions --install-extension ms-python.python 
#   code-server --extensions-dir=/.vscode/extensions --install-extension detachhead.basedpyright
fi